version: '2.3'

services:

  mysql:
    image: gennyproject/mysql:8x
    container_name: mysql
    environment:
      - MYSQL_URL=mysql
      - MYSQL_DB=gennydb
      - MYSQL_PORT=3306
      - MYSQL_ALLOW_EMPTY=
      - MYSQL_DATABASE=gennydb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    #    env_file:
    #      - ${ENV_FILE}
    volumes:
      - mysql_data:/var/lib/mysql:delegated
    networks:
      - mainproxy
    ports:
      - ${MYSQL_PORT}:${MYSQL_INTERNAL_PORT}
    command: --sql_mode=""
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  fyodor:
    depends_on:
      mysql:
        condition: service_healthy
    image: gennyproject/fyodor:latest
    #    container_name: bootq 
    #    container_name: bootq 
    #    container_name: bootq 
    volumes:
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart
    env_file:
      - ${ENV_FILE}
    environment:
      #      - VIRTUAL_HOST=bootq.*
      - VIRTUAL_PORT=${FYODOR_INTERNAL_PORT}
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
      - DEBUG_SUSPEND=n
      #    - DDT_URL=http://bridge:8089
      - FULL_MYSQL_URL=jdbc:mysql://mysql/gennydb
      - GENNY_KAFKA_URL=http://localhost:${KAFKA_PORT}
      - GENNY_REALM=internmatch
      - GENNY_CLIENT_ID=${GENNY_CLIENT_ID}
      - GENNY_CLIENT_SECRET=${GENNY_CLIENT_SECRET}
      - GENNY_SERVICE_USERNAME=${GENNY_SERVICE_USERNAME}
      - GENNY_SERVICE_PASSWORD=${GENNY_SERVICE_PASSWORD}
      - GENNY_KEYCLOAK_URL=${GENNY_KEYCLOAK_URL:https://keycloak.gada.io}
      - GENNY_API_URL=http://localhost:${FYODOR_INTERNAL_PORT}
      - GENNY_MYSQL_FULL_URL=alyson.genny.life:${MYSQL_PORT}/gennydb?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    ports:
      - ${FYODOR_PORT}:${FYODOR_INTERNAL_PORT}
      - ${FYODOR_DEBUG_PORT}:${FYODOR_INTERNAL_DEBUG_PORT}
    links:
      - mysql:mysql
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${FYODOR_INTERNAL_PORT}/version"
        ]
      interval: 10s
      timeout: 10s
      retries: 100
    restart: unless-stopped
    networks:
      - mainproxy

volumes:
  abn_tmp:
  mysql_data:
  minio_conf:
  minio_data:
  maildata:
    driver: local
  mailstate:
    driver: local
networks:
  mainproxy:
    driver: bridge
